/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabrestaurante;

import java.awt.Component;
import java.awt.Image;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Pedr0xh
 */
public class Cardapio extends javax.swing.JFrame {

    /**
     * Creates new form Cardapio
     */
    public Cardapio() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);


    // Painel principal com BoxLayout na vertical
    JPanel painelPrincipal = new JPanel();
    painelPrincipal.setLayout(new BoxLayout(painelPrincipal, BoxLayout.Y_AXIS));

    // Adiciona os itens no painel principal
    painelPrincipal.add(criarItemCardapio("C:\\Users\\podes\\Downloads\\burger.png", "Hamburger Simples"));
    painelPrincipal.add(criarItemCardapio("C:\\Users\\podes\\Downloads\\Vegano.png", "Hamburger Vegano"));
    painelPrincipal.add(criarItemCardapio("C:\\Users\\podes\\Downloads\\Cheddar.png", "Hamburger Cheddar"));
    painelPrincipal.add(criarItemCardapio("C:\\Users\\podes\\Downloads\\Turbo.png", "Hamburger Turbo"));
    painelPrincipal.add(criarItemCardapio("C:\\Users\\podes\\Downloads\\600ml.png", "Refrigerante 600ml"));
    painelPrincipal.add(criarItemCardapio("C:\\Users\\podes\\Downloads\\600mlzero.png", "Refrigerante Zero"));
    painelPrincipal.add(criarItemCardapio("C:\\Users\\podes\\Downloads\\Sorvete.png", "Sorvete")); // NOI18N
    painelPrincipal.add(criarItemCardapio("C:\\Users\\podes\\Downloads\\Bolo.png", "Bolo Brigadeiro")); // NOI18N


    // Coloca tudo em um JScrollPane
    JScrollPane scrollPane = new JScrollPane(painelPrincipal);
    scrollPane.getVerticalScrollBar().setUnitIncrement(16); // rolagem suave

    // Adiciona à janela
    getContentPane().add(scrollPane);

    pack();
    setSize(300, 500); // tamanho da janela
    setLocationRelativeTo(null); // centraliza
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\podes\\Downloads\\burger.png")); // NOI18N
        jLabel1.setText("Hamburger Simples");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\podes\\Downloads\\Vegano.png")); // NOI18N
        jLabel2.setText("Hamburger Vegano");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\podes\\Downloads\\Cheddar.png")); // NOI18N
        jLabel3.setText("Hamburger Cheddar");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\podes\\Downloads\\Turbo.png")); // NOI18N
        jLabel4.setText("Hamburger Turbo");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\podes\\Downloads\\600ml.png")); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\podes\\Downloads\\600mlzero.png")); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\podes\\Downloads\\Sorvete.png")); // NOI18N
        jLabel7.setText("Sorvete");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\podes\\Downloads\\Bolo.png")); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cardapio().setVisible(true);
            }
        });
    }
    
    private ImageIcon redimensionarImagem(String caminho, int largura, int altura) {
    ImageIcon icon = new ImageIcon(caminho);
    Image img = icon.getImage().getScaledInstance(largura, altura, Image.SCALE_SMOOTH);
    return new ImageIcon(img);
}

    private JPanel criarItemCardapio(String caminhoImagem, String nomeProduto) {
    String descricao = obterDescricaoProduto(nomeProduto);

    JPanel itemPanel = new JPanel();
    itemPanel.setLayout(new BoxLayout(itemPanel, BoxLayout.X_AXIS));
    itemPanel.setAlignmentX(Component.LEFT_ALIGNMENT);

    // Imagem redimensionada
    JLabel imagemLabel = new JLabel(redimensionarImagem(caminhoImagem, 150, 100));
    imagemLabel.setAlignmentY(Component.TOP_ALIGNMENT);

    // Painel de texto (nome + descrição)
    JPanel textoPanel = new JPanel();
    textoPanel.setLayout(new BoxLayout(textoPanel, BoxLayout.Y_AXIS));
    textoPanel.setAlignmentY(Component.TOP_ALIGNMENT);

    JLabel nomeLabel = new JLabel("<html><b>" + nomeProduto + "</b></html>");
    JLabel descricaoLabel = new JLabel("<html><i>" + descricao + "</i></html>");

    textoPanel.add(nomeLabel);
    textoPanel.add(descricaoLabel);

    itemPanel.add(imagemLabel);
    itemPanel.add(Box.createHorizontalStrut(10)); // espaço entre imagem e texto
    itemPanel.add(textoPanel);

    return itemPanel;
}
    private String obterDescricaoProduto(String nomeProduto) {
    switch (nomeProduto) {
        case "Hamburger Simples":
            return "Pão, carne e queijo. Clássico e delicioso!";
        case "Hamburger Vegano":
            return "Feito com ingredientes 100% vegetais.";
        case "Hamburger Cheddar":
            return "Hamburguer com generosa porção de cheddar.";
        case "Hamburger Turbo":
            return "Duplo burger, bacon e molho especial.";
        case "Refrigerante 600ml":
            return "Sua bebida preferida para acompanhar.";
        case "Refrigerante Zero":
            return "Sabor com zero açúcar.";
        case "Sorvete":
            return "Sabores variados, perfeito para sobremesa.";
        case "Bolo Brigadeiro":
            return "Camadas de chocolate e brigadeiro cremoso.";
        default:
            return "Produto delicioso.";
    }
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
