/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabrestaurante;

import dao.PedidoDao;
import dao.ProdutoDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Pedido;
import modelo.Produto;

/**
 *
 * @author Pedr0xh
 */
public class Carrinho extends javax.swing.JFrame {

    /**
     * Creates new form Carrinho
     */
    public Carrinho() {
        initComponents();
        carregarProdutos();
        DefaultTableModel modelo = (DefaultTableModel) tblCarrinho.getModel();
        modelo.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarrinho = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbProduto = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        btnVerPedidos = new javax.swing.JButton();
        btnCardapio = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("Carrinho ");

        tblCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblCarrinho);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Valor total:");

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setText("Limpar carrinho");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnFinalizar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnFinalizar.setText("Finalizar pedido");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTotal.setText("R$ 00,00");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setText("Produto:");

        cmbProduto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        cmbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton3.setText("Pedir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnVerPedidos.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnVerPedidos.setText("Ver Pedidos");
        btnVerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPedidosActionPerformed(evt);
            }
        });

        btnCardapio.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCardapio.setText("Cardapio");
        btnCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardapioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addGap(97, 97, 97)
                                    .addComponent(btnFinalizar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3)
                            .addComponent(btnVerPedidos)
                            .addComponent(btnCardapio))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(btnCardapio)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotal))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnFinalizar)
                    .addComponent(btnVerPedidos))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) tblCarrinho.getModel();
    modelo.setRowCount(0); // Remove todas as linhas
    lblTotal.setText("R$ 00,00");    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nomeProduto = cmbProduto.getSelectedItem().toString();
        
    ProdutoDao pDao = new ProdutoDao();
    Produto p = pDao.carregarNome(nomeProduto);

    if (p != null && p.getQuantidade() >= 1) {
        DefaultTableModel modelo = (DefaultTableModel) tblCarrinho.getModel();
        boolean itemExiste = false;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String nomeNaTabela = modelo.getValueAt(i, 0).toString();

            if (nomeNaTabela.equals(nomeProduto)) {
                // Já existe na tabela, então incrementa a quantidade
                int quantidadeAtual = Integer.parseInt(modelo.getValueAt(i, 1).toString());
                int novaQuantidade = quantidadeAtual + 1;
                double novoValor = p.getPreco() * novaQuantidade;

                modelo.setValueAt(novaQuantidade, i, 1);
                modelo.setValueAt(String.format("R$ %.2f", novoValor), i, 2);

                itemExiste = true;
                break;
            }
        }

        // Se não existe ainda, adiciona
        if (!itemExiste) {
            modelo.addRow(new Object[]{nomeProduto, 1, String.format("R$ %.2f", p.getPreco())});
        }

        atualizarValorTotal();

    } else {
        JOptionPane.showMessageDialog(this, "Produto não disponível ou fora de estoque.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblCarrinho.getModel();

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Adicione itens ao carrinho primeiro.");
            return;
        }

        double valorTotal = 0.0;
        ArrayList<Produto> produtosDoPedido = new ArrayList<>();

        ProdutoDao pDao = new ProdutoDao();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String nomeProduto = modelo.getValueAt(i, 0).toString();
            int quantidade = Integer.parseInt(modelo.getValueAt(i, 1).toString());

            String valorStr = modelo.getValueAt(i, 2).toString().replace("R$", "").replace(",", ".").trim();
            double valorItem = Double.parseDouble(valorStr);
            valorTotal += valorItem;

            Produto p = pDao.carregarNome(nomeProduto);
            if (p != null) {
                p.setQuantidade(quantidade);
                produtosDoPedido.add(p);
            }
        }

        int mesa = 1;
        Pedido pedido = new Pedido(valorTotal, mesa, produtosDoPedido);

        PedidoDao dao = new PedidoDao();
        dao.inserir(pedido); // Aqui você pode estender o método para salvar os produtos também

        JOptionPane.showMessageDialog(this, "Pedido finalizado com sucesso!");

        modelo.setRowCount(0);
        lblTotal.setText("R$ 00,00");
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPedidosActionPerformed
        new Pedidos().setVisible(true);
    }//GEN-LAST:event_btnVerPedidosActionPerformed

    private void btnCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardapioActionPerformed
        new Cardapio().setVisible(true);
    }//GEN-LAST:event_btnCardapioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrinho().setVisible(true);
            }
        });
    }
    private void atualizarValorTotal() {
        DefaultTableModel modelo = (DefaultTableModel) tblCarrinho.getModel();
        double total = 0.0;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String valorStr = modelo.getValueAt(i, 2).toString().replace("R$", "").replace(",", ".").trim();
            total += Double.parseDouble(valorStr);
        }

        lblTotal.setText(String.format("R$ %.2f", total));
    }

    private void carregarProdutos() {
        ProdutoDao pDao = new ProdutoDao();
        ArrayList<Produto> produtos = pDao.carregarTodos();

        cmbProduto.removeAllItems(); // Limpa os itens anteriores para evitar duplicatas

        for (Produto p : produtos) {
            cmbProduto.addItem(p.getNome()); // Adiciona apenas o nome do produto ao ComboBox
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCardapio;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnVerPedidos;
    private javax.swing.JComboBox<String> cmbProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCarrinho;
    // End of variables declaration//GEN-END:variables
}
